import fs from 'node:fs';import path from 'node:path';import {describe,expect,it} from 'vitest';
const root=process.cwd();const read=(file:string)=>fs.readFileSync(path.join(root,file),'utf8');
describe('Admin Centre launch security contract',()=>{
  const page=read('src/pages/Admin.tsx'),ui=read('src/components/Admin/AdminCentrePages.tsx'),migration=read('supabase/migrations/20260819153000_admin_centre_launch.sql'),edge=read('supabase/functions/admin-account-action/index.ts');
  it('has only the five approved routed destinations',()=>{for(const route of ['overview','customers','subscriptions-payments','events','account-lifecycle'])expect(page).toContain(`id: '${route}'`);for(const removed of ['AdminInvitationTemplates','AdminVenueTemplates','AdminSystemSettings','AdminNotificationSettings','AdminLogs'])expect(page).not.toContain(removed);});
  it('protects reporting and mutations with owner-admin and service-role checks',()=>{expect(migration).toContain('IF NOT public.is_owner_admin()');expect(migration).toContain("auth.role()<>'service_role'");expect(edge).toContain("userClient.rpc('is_owner_admin')");expect(edge).toContain('SUPABASE_SERVICE_ROLE_KEY');expect(edge).toContain('Recent administrator verification is required.');});
  it('enforces suspension in the shared operational check and audits sensitive actions',()=>{expect(migration).toContain("c.status<>'suspended'");expect(migration).toContain('admin_action_audit');for(const field of ['administrator_id','action','target_id','reason','previous_state','new_state','result','safe_error_reference'])expect(migration).toContain(field);});
  it('does not expose raw lifecycle errors or secret fields in the interface',()=>{expect(ui).not.toContain('rpcError.message');for(const forbidden of ['Resend API key','service-role key','From-email field','Raw Edge Function Logs'])expect(ui).not.toContain(forbidden);expect(ui).toContain('Admin data is temporarily unavailable');});
  it('requires strong confirmation for permanent deletion and never invokes it automatically',()=>{expect(ui).toContain('PERMANENTLY DELETE');expect(ui).toContain('I understand this is irreversible');expect(ui).toMatch(/action:\s*["']permanently_delete_now["']/);expect(edge).toContain("action==='permanently_delete_now'");});
  it('preserves the approved RSVP bundle definition',()=>{const prices=read('src/lib/stripePrices.ts');expect(prices).toMatch(/100/);const rsvp=read('src/components/Dashboard/RsvpActivationModal.tsx');expect(rsvp).toMatch(/400/);expect(rsvp).toMatch(/unlimited email/i);});
  it('does not alter the customer Invitations product route',()=>{const app=read('src/App.tsx');expect(app).toContain('/invitations-cards');expect(app).toContain('ProductInvitationsCards');});
  it('includes responsive drawer, focus and reduced-motion support',()=>{const css=read('src/pages/Admin.module.css');expect(css).toContain('@media(max-width:1023px)');expect(css).toContain('focus-visible');expect(css).toContain('prefers-reduced-motion');});
});
