// AUTO-GENERATED by scripts/generate-gallery-backgrounds.mjs — do not edit by hand.
// Owned, locally-stored SVG backgrounds served from /public/gallery-backgrounds.
export interface GalleryBackgroundPreset {
  slug: string;
  name: string;
  category: string;
  url: string;
}

export const GALLERY_BACKGROUND_CATEGORIES = [
  "Elegant & Luxury",
  "Floral & Romantic",
  "Modern & Minimal",
  "Birthday & Celebration",
  "Corporate & Neutral",
  "Dark & Evening"
] as const;

export const GALLERY_BACKGROUND_PRESETS: GalleryBackgroundPreset[] = [
  {
    "slug": "elegant-champagne-silk",
    "name": "Champagne Silk",
    "category": "Elegant & Luxury",
    "url": "/gallery-backgrounds/elegant-champagne-silk.svg"
  },
  {
    "slug": "elegant-ivory-damask",
    "name": "Ivory Damask",
    "category": "Elegant & Luxury",
    "url": "/gallery-backgrounds/elegant-ivory-damask.svg"
  },
  {
    "slug": "elegant-gold-marble",
    "name": "Gilded Marble",
    "category": "Elegant & Luxury",
    "url": "/gallery-backgrounds/elegant-gold-marble.svg"
  },
  {
    "slug": "elegant-blush-pearl",
    "name": "Blush Pearl",
    "category": "Elegant & Luxury",
    "url": "/gallery-backgrounds/elegant-blush-pearl.svg"
  },
  {
    "slug": "floral-rose-garden",
    "name": "Rose Garden",
    "category": "Floral & Romantic",
    "url": "/gallery-backgrounds/floral-rose-garden.svg"
  },
  {
    "slug": "floral-eucalyptus",
    "name": "Eucalyptus",
    "category": "Floral & Romantic",
    "url": "/gallery-backgrounds/floral-eucalyptus.svg"
  },
  {
    "slug": "floral-peony-blush",
    "name": "Peony Blush",
    "category": "Floral & Romantic",
    "url": "/gallery-backgrounds/floral-peony-blush.svg"
  },
  {
    "slug": "floral-lavender-field",
    "name": "Lavender Field",
    "category": "Floral & Romantic",
    "url": "/gallery-backgrounds/floral-lavender-field.svg"
  },
  {
    "slug": "modern-linen-white",
    "name": "Linen White",
    "category": "Modern & Minimal",
    "url": "/gallery-backgrounds/modern-linen-white.svg"
  },
  {
    "slug": "modern-soft-grid",
    "name": "Soft Grid",
    "category": "Modern & Minimal",
    "url": "/gallery-backgrounds/modern-soft-grid.svg"
  },
  {
    "slug": "modern-warm-sand",
    "name": "Warm Sand",
    "category": "Modern & Minimal",
    "url": "/gallery-backgrounds/modern-warm-sand.svg"
  },
  {
    "slug": "modern-mist-gradient",
    "name": "Morning Mist",
    "category": "Modern & Minimal",
    "url": "/gallery-backgrounds/modern-mist-gradient.svg"
  },
  {
    "slug": "celebration-confetti-cream",
    "name": "Confetti Cream",
    "category": "Birthday & Celebration",
    "url": "/gallery-backgrounds/celebration-confetti-cream.svg"
  },
  {
    "slug": "celebration-balloon-pastel",
    "name": "Pastel Party",
    "category": "Birthday & Celebration",
    "url": "/gallery-backgrounds/celebration-balloon-pastel.svg"
  },
  {
    "slug": "celebration-golden-sparkle",
    "name": "Golden Sparkle",
    "category": "Birthday & Celebration",
    "url": "/gallery-backgrounds/celebration-golden-sparkle.svg"
  },
  {
    "slug": "celebration-citrus-pop",
    "name": "Citrus Pop",
    "category": "Birthday & Celebration",
    "url": "/gallery-backgrounds/celebration-citrus-pop.svg"
  },
  {
    "slug": "corporate-slate-lines",
    "name": "Slate Lines",
    "category": "Corporate & Neutral",
    "url": "/gallery-backgrounds/corporate-slate-lines.svg"
  },
  {
    "slug": "corporate-navy-fade",
    "name": "Navy Fade",
    "category": "Corporate & Neutral",
    "url": "/gallery-backgrounds/corporate-navy-fade.svg"
  },
  {
    "slug": "corporate-stone-grey",
    "name": "Stone Grey",
    "category": "Corporate & Neutral",
    "url": "/gallery-backgrounds/corporate-stone-grey.svg"
  },
  {
    "slug": "corporate-quiet-teal",
    "name": "Quiet Teal",
    "category": "Corporate & Neutral",
    "url": "/gallery-backgrounds/corporate-quiet-teal.svg"
  },
  {
    "slug": "evening-midnight-velvet",
    "name": "Midnight Velvet",
    "category": "Dark & Evening",
    "url": "/gallery-backgrounds/evening-midnight-velvet.svg"
  },
  {
    "slug": "evening-charcoal-gold",
    "name": "Charcoal & Gold",
    "category": "Dark & Evening",
    "url": "/gallery-backgrounds/evening-charcoal-gold.svg"
  },
  {
    "slug": "evening-plum-dusk",
    "name": "Plum Dusk",
    "category": "Dark & Evening",
    "url": "/gallery-backgrounds/evening-plum-dusk.svg"
  },
  {
    "slug": "evening-deep-emerald",
    "name": "Deep Emerald",
    "category": "Dark & Evening",
    "url": "/gallery-backgrounds/evening-deep-emerald.svg"
  }
];

export const isGalleryBackgroundPreset = (url: string | null | undefined): boolean =>
  !!url && GALLERY_BACKGROUND_PRESETS.some(p => p.url === url);
