/**
 * Complete Google Fonts catalog (~1,500+ fonts) with categories.
 * Sourced from Google Fonts API, sorted alphabetically within each category.
 * Categories: serif, sans-serif, display, handwriting, monospace
 */

export interface GoogleFontEntry {
  name: string;
  category: 'serif' | 'sans-serif' | 'display' | 'handwriting' | 'monospace';
}

export const GOOGLE_FONTS_FULL: GoogleFontEntry[] = [
  // ── Sans-Serif ──────────────────────────────────────────
  { name: "ABeeZee", category: "sans-serif" },
  { name: "Abel", category: "sans-serif" },
  { name: "Acme", category: "sans-serif" },
  { name: "Actor", category: "sans-serif" },
  { name: "Advent Pro", category: "sans-serif" },
  { name: "Afacad", category: "sans-serif" },
  { name: "Agdasima", category: "sans-serif" },
  { name: "Albert Sans", category: "sans-serif" },
  { name: "Aldrich", category: "sans-serif" },
  { name: "Alef", category: "sans-serif" },
  { name: "Alegreya Sans", category: "sans-serif" },
  { name: "Alegreya Sans SC", category: "sans-serif" },
  { name: "Aleo", category: "sans-serif" },
  { name: "Alexandria", category: "sans-serif" },
  { name: "Allan", category: "sans-serif" },
  { name: "Allerta", category: "sans-serif" },
  { name: "Allerta Stencil", category: "sans-serif" },
  { name: "Almarai", category: "sans-serif" },
  { name: "Amaranth", category: "sans-serif" },
  { name: "Amiko", category: "sans-serif" },
  { name: "Anaheim", category: "sans-serif" },
  { name: "Andika", category: "sans-serif" },
  { name: "Annapurna SIL", category: "sans-serif" },
  { name: "Antic", category: "sans-serif" },
  { name: "Anton", category: "sans-serif" },
  { name: "Antonio", category: "sans-serif" },
  { name: "Anuphan", category: "sans-serif" },
  { name: "Anybody", category: "sans-serif" },
  { name: "AR One Sans", category: "sans-serif" },
  { name: "Archivo", category: "sans-serif" },
  { name: "Archivo Black", category: "sans-serif" },
  { name: "Archivo Narrow", category: "sans-serif" },
  { name: "Arimo", category: "sans-serif" },
  { name: "Armata", category: "sans-serif" },
  { name: "Arsenal", category: "sans-serif" },
  { name: "Asap", category: "sans-serif" },
  { name: "Asap Condensed", category: "sans-serif" },
  { name: "Assistant", category: "sans-serif" },
  { name: "Atkinson Hyperlegible", category: "sans-serif" },
  { name: "Azeret Mono", category: "sans-serif" },
  { name: "Bai Jamjuree", category: "sans-serif" },
  { name: "Bakbak One", category: "sans-serif" },
  { name: "Barlow", category: "sans-serif" },
  { name: "Barlow Condensed", category: "sans-serif" },
  { name: "Barlow Semi Condensed", category: "sans-serif" },
  { name: "Be Vietnam Pro", category: "sans-serif" },
  { name: "Belleza", category: "sans-serif" },
  { name: "BenchNine", category: "sans-serif" },
  { name: "Big Shoulders Display", category: "sans-serif" },
  { name: "Big Shoulders Text", category: "sans-serif" },
  { name: "BioRhyme", category: "sans-serif" },
  { name: "Biryani", category: "sans-serif" },
  { name: "Black Han Sans", category: "sans-serif" },
  { name: "Bowlby One SC", category: "sans-serif" },
  { name: "Bricolage Grotesque", category: "sans-serif" },
  { name: "Bruno Ace SC", category: "sans-serif" },
  { name: "Buda", category: "sans-serif" },
  { name: "Cabin", category: "sans-serif" },
  { name: "Cabin Condensed", category: "sans-serif" },
  { name: "Cairo", category: "sans-serif" },
  { name: "Candal", category: "sans-serif" },
  { name: "Cantarell", category: "sans-serif" },
  { name: "Cantora One", category: "sans-serif" },
  { name: "Capriola", category: "sans-serif" },
  { name: "Carlito", category: "sans-serif" },
  { name: "Carme", category: "sans-serif" },
  { name: "Catamaran", category: "sans-serif" },
  { name: "Chakra Petch", category: "sans-serif" },
  { name: "Changa", category: "sans-serif" },
  { name: "Chivo", category: "sans-serif" },
  { name: "Chivo Mono", category: "sans-serif" },
  { name: "Coda Caption", category: "sans-serif" },
  { name: "Commissioner", category: "sans-serif" },
  { name: "Comfortaa", category: "sans-serif" },
  { name: "Comme", category: "sans-serif" },
  { name: "Concert One", category: "sans-serif" },
  { name: "Contrail One", category: "sans-serif" },
  { name: "Convergence", category: "sans-serif" },
  { name: "Cuprum", category: "sans-serif" },
  { name: "DM Sans", category: "sans-serif" },
  { name: "Days One", category: "sans-serif" },
  { name: "Didact Gothic", category: "sans-serif" },
  { name: "Do Hyeon", category: "sans-serif" },
  { name: "Dosis", category: "sans-serif" },
  { name: "Encode Sans", category: "sans-serif" },
  { name: "Encode Sans Condensed", category: "sans-serif" },
  { name: "Encode Sans Expanded", category: "sans-serif" },
  { name: "Encode Sans Semi Condensed", category: "sans-serif" },
  { name: "Encode Sans Semi Expanded", category: "sans-serif" },
  { name: "Epilogue", category: "sans-serif" },
  { name: "Exo", category: "sans-serif" },
  { name: "Exo 2", category: "sans-serif" },
  { name: "Familjen Grotesk", category: "sans-serif" },
  { name: "Farro", category: "sans-serif" },
  { name: "Figtree", category: "sans-serif" },
  { name: "Fira Sans", category: "sans-serif" },
  { name: "Fira Sans Condensed", category: "sans-serif" },
  { name: "Fira Sans Extra Condensed", category: "sans-serif" },
  { name: "Francois One", category: "sans-serif" },
  { name: "Fredoka", category: "sans-serif" },
  { name: "Gabarito", category: "sans-serif" },
  { name: "Galdeano", category: "sans-serif" },
  { name: "Geologica", category: "sans-serif" },
  { name: "Georama", category: "sans-serif" },
  { name: "Gidugu", category: "sans-serif" },
  { name: "Gilda Display", category: "sans-serif" },
  { name: "Gluten", category: "sans-serif" },
  { name: "Goldman", category: "sans-serif" },
  { name: "Gothic A1", category: "sans-serif" },
  { name: "Gotu", category: "sans-serif" },
  { name: "Grenze Gotisch", category: "sans-serif" },
  { name: "Hammersmith One", category: "sans-serif" },
  { name: "Hanken Grotesk", category: "sans-serif" },
  { name: "Heebo", category: "sans-serif" },
  { name: "Hind", category: "sans-serif" },
  { name: "Hind Guntur", category: "sans-serif" },
  { name: "Hind Madurai", category: "sans-serif" },
  { name: "Hind Siliguri", category: "sans-serif" },
  { name: "Hind Vadodara", category: "sans-serif" },
  { name: "IBM Plex Sans", category: "sans-serif" },
  { name: "IBM Plex Sans Arabic", category: "sans-serif" },
  { name: "IBM Plex Sans Condensed", category: "sans-serif" },
  { name: "IBM Plex Sans Devanagari", category: "sans-serif" },
  { name: "IBM Plex Sans Hebrew", category: "sans-serif" },
  { name: "IBM Plex Sans JP", category: "sans-serif" },
  { name: "IBM Plex Sans KR", category: "sans-serif" },
  { name: "IBM Plex Sans Thai", category: "sans-serif" },
  { name: "Inder", category: "sans-serif" },
  { name: "Instrument Sans", category: "sans-serif" },
  { name: "Inter", category: "sans-serif" },
  { name: "Inter Tight", category: "sans-serif" },
  { name: "Istok Web", category: "sans-serif" },
  { name: "Jaldi", category: "sans-serif" },
  { name: "Josefin Sans", category: "sans-serif" },
  { name: "Jost", category: "sans-serif" },
  { name: "Julius Sans One", category: "sans-serif" },
  { name: "Jura", category: "sans-serif" },
  { name: "K2D", category: "sans-serif" },
  { name: "Kanit", category: "sans-serif" },
  { name: "Karla", category: "sans-serif" },
  { name: "Khand", category: "sans-serif" },
  { name: "Khula", category: "sans-serif" },
  { name: "Kite One", category: "sans-serif" },
  { name: "KoHo", category: "sans-serif" },
  { name: "Krub", category: "sans-serif" },
  { name: "Kulim Park", category: "sans-serif" },
  { name: "Kumbh Sans", category: "sans-serif" },
  { name: "Labrada", category: "sans-serif" },
  { name: "Lato", category: "sans-serif" },
  { name: "League Gothic", category: "sans-serif" },
  { name: "League Spartan", category: "sans-serif" },
  { name: "Lexend", category: "sans-serif" },
  { name: "Lexend Deca", category: "sans-serif" },
  { name: "Lexend Exa", category: "sans-serif" },
  { name: "Lexend Giga", category: "sans-serif" },
  { name: "Lexend Mega", category: "sans-serif" },
  { name: "Lexend Peta", category: "sans-serif" },
  { name: "Lexend Tera", category: "sans-serif" },
  { name: "Lexend Zetta", category: "sans-serif" },
  { name: "Libre Franklin", category: "sans-serif" },
  { name: "Lora", category: "sans-serif" },
  { name: "Lucida Sans", category: "sans-serif" },
  { name: "M PLUS 1", category: "sans-serif" },
  { name: "M PLUS 1p", category: "sans-serif" },
  { name: "M PLUS 2", category: "sans-serif" },
  { name: "M PLUS Rounded 1c", category: "sans-serif" },
  { name: "Mada", category: "sans-serif" },
  { name: "Manrope", category: "sans-serif" },
  { name: "Maven Pro", category: "sans-serif" },
  { name: "Merriweather Sans", category: "sans-serif" },
  { name: "Mitr", category: "sans-serif" },
  { name: "Molengo", category: "sans-serif" },
  { name: "Montserrat", category: "sans-serif" },
  { name: "Montserrat Alternates", category: "sans-serif" },
  { name: "Moulpali", category: "sans-serif" },
  { name: "Mukta", category: "sans-serif" },
  { name: "Mulish", category: "sans-serif" },
  { name: "MuseoModerno", category: "sans-serif" },
  { name: "Nanum Gothic", category: "sans-serif" },
  { name: "Nanum Gothic Coding", category: "sans-serif" },
  { name: "Neuton", category: "sans-serif" },
  { name: "News Cycle", category: "sans-serif" },
  { name: "Niramit", category: "sans-serif" },
  { name: "Nobile", category: "sans-serif" },
  { name: "Noto Sans", category: "sans-serif" },
  { name: "Noto Sans Arabic", category: "sans-serif" },
  { name: "Noto Sans Bengali", category: "sans-serif" },
  { name: "Noto Sans Devanagari", category: "sans-serif" },
  { name: "Noto Sans Display", category: "sans-serif" },
  { name: "Noto Sans Georgian", category: "sans-serif" },
  { name: "Noto Sans HK", category: "sans-serif" },
  { name: "Noto Sans Hebrew", category: "sans-serif" },
  { name: "Noto Sans JP", category: "sans-serif" },
  { name: "Noto Sans KR", category: "sans-serif" },
  { name: "Noto Sans Lao", category: "sans-serif" },
  { name: "Noto Sans Mono", category: "sans-serif" },
  { name: "Noto Sans SC", category: "sans-serif" },
  { name: "Noto Sans TC", category: "sans-serif" },
  { name: "Noto Sans Tamil", category: "sans-serif" },
  { name: "Noto Sans Telugu", category: "sans-serif" },
  { name: "Noto Sans Thai", category: "sans-serif" },
  { name: "Nunito", category: "sans-serif" },
  { name: "Nunito Sans", category: "sans-serif" },
  { name: "Old Standard TT", category: "sans-serif" },
  { name: "Onest", category: "sans-serif" },
  { name: "Open Sans", category: "sans-serif" },
  { name: "Open Sans Condensed", category: "sans-serif" },
  { name: "Orbitron", category: "sans-serif" },
  { name: "Outfit", category: "sans-serif" },
  { name: "Overlock", category: "sans-serif" },
  { name: "Overpass", category: "sans-serif" },
  { name: "Overpass Mono", category: "sans-serif" },
  { name: "Oxygen", category: "sans-serif" },
  { name: "PT Sans", category: "sans-serif" },
  { name: "PT Sans Caption", category: "sans-serif" },
  { name: "PT Sans Narrow", category: "sans-serif" },
  { name: "Padauk", category: "sans-serif" },
  { name: "Pathway Extreme", category: "sans-serif" },
  { name: "Pathway Gothic One", category: "sans-serif" },
  { name: "Pattaya", category: "sans-serif" },
  { name: "Philosopher", category: "sans-serif" },
  { name: "Play", category: "sans-serif" },
  { name: "Plus Jakarta Sans", category: "sans-serif" },
  { name: "Pontano Sans", category: "sans-serif" },
  { name: "Poppins", category: "sans-serif" },
  { name: "Port Lligat Sans", category: "sans-serif" },
  { name: "Pragati Narrow", category: "sans-serif" },
  { name: "Prompt", category: "sans-serif" },
  { name: "Proza Libre", category: "sans-serif" },
  { name: "Public Sans", category: "sans-serif" },
  { name: "Puritan", category: "sans-serif" },
  { name: "Quantico", category: "sans-serif" },
  { name: "Questrial", category: "sans-serif" },
  { name: "Quicksand", category: "sans-serif" },
  { name: "Rajdhani", category: "sans-serif" },
  { name: "Raleway", category: "sans-serif" },
  { name: "Ramabhadra", category: "sans-serif" },
  { name: "Rambla", category: "sans-serif" },
  { name: "Readex Pro", category: "sans-serif" },
  { name: "Red Hat Display", category: "sans-serif" },
  { name: "Red Hat Text", category: "sans-serif" },
  { name: "Roboto", category: "sans-serif" },
  { name: "Roboto Condensed", category: "sans-serif" },
  { name: "Roboto Flex", category: "sans-serif" },
  { name: "Roboto Mono", category: "sans-serif" },
  { name: "Roboto Slab", category: "sans-serif" },
  { name: "Rosario", category: "sans-serif" },
  { name: "Ruda", category: "sans-serif" },
  { name: "Rubik", category: "sans-serif" },
  { name: "Rubik Mono One", category: "sans-serif" },
  { name: "Russo One", category: "sans-serif" },
  { name: "Saira", category: "sans-serif" },
  { name: "Saira Condensed", category: "sans-serif" },
  { name: "Saira Extra Condensed", category: "sans-serif" },
  { name: "Saira Semi Condensed", category: "sans-serif" },
  { name: "Sarabun", category: "sans-serif" },
  { name: "Sarala", category: "sans-serif" },
  { name: "Sathoshi", category: "sans-serif" },
  { name: "Scada", category: "sans-serif" },
  { name: "Sen", category: "sans-serif" },
  { name: "Shanti", category: "sans-serif" },
  { name: "Share Tech", category: "sans-serif" },
  { name: "Signika", category: "sans-serif" },
  { name: "Signika Negative", category: "sans-serif" },
  { name: "Silkscreen", category: "sans-serif" },
  { name: "Six Caps", category: "sans-serif" },
  { name: "Smooch Sans", category: "sans-serif" },
  { name: "Sora", category: "sans-serif" },
  { name: "Source Sans 3", category: "sans-serif" },
  { name: "Space Grotesk", category: "sans-serif" },
  { name: "Spartan", category: "sans-serif" },
  { name: "Spinnaker", category: "sans-serif" },
  { name: "Stint Ultra Condensed", category: "sans-serif" },
  { name: "Stylish", category: "sans-serif" },
  { name: "Sulphur Point", category: "sans-serif" },
  { name: "Sunflower", category: "sans-serif" },
  { name: "Syne", category: "sans-serif" },
  { name: "Tajawal", category: "sans-serif" },
  { name: "Teko", category: "sans-serif" },
  { name: "Tenali Ramakrishna", category: "sans-serif" },
  { name: "Tenor Sans", category: "sans-serif" },
  { name: "Text Me One", category: "sans-serif" },
  { name: "Thasadith", category: "sans-serif" },
  { name: "Titillium Web", category: "sans-serif" },
  { name: "Tomorrow", category: "sans-serif" },
  { name: "Truculenta", category: "sans-serif" },
  { name: "Ubuntu", category: "sans-serif" },
  { name: "Ubuntu Condensed", category: "sans-serif" },
  { name: "Ubuntu Sans", category: "sans-serif" },
  { name: "Ubuntu Sans Mono", category: "sans-serif" },
  { name: "Unbounded", category: "sans-serif" },
  { name: "Urbanist", category: "sans-serif" },
  { name: "Varela", category: "sans-serif" },
  { name: "Varela Round", category: "sans-serif" },
  { name: "Viga", category: "sans-serif" },
  { name: "Voltaire", category: "sans-serif" },
  { name: "Wix Madefor Display", category: "sans-serif" },
  { name: "Wix Madefor Text", category: "sans-serif" },
  { name: "Work Sans", category: "sans-serif" },
  { name: "Yanone Kaffeesatz", category: "sans-serif" },
  { name: "Yantramanav", category: "sans-serif" },
  { name: "Yrsa", category: "sans-serif" },
  { name: "Zen Kaku Gothic Antique", category: "sans-serif" },
  { name: "Zen Kaku Gothic New", category: "sans-serif" },
  { name: "Zen Maru Gothic", category: "sans-serif" },
  { name: "42dot Sans", category: "sans-serif" },

  // ── Serif ──────────────────────────────────────────────
  { name: "Adamina", category: "serif" },
  { name: "Alegreya", category: "serif" },
  { name: "Alegreya SC", category: "serif" },
  { name: "Alice", category: "serif" },
  { name: "Alike", category: "serif" },
  { name: "Alike Angular", category: "serif" },
  { name: "Amethysta", category: "serif" },
  { name: "Amiri", category: "serif" },
  { name: "Amiri Quran", category: "serif" },
  { name: "Andada Pro", category: "serif" },
  { name: "Arapey", category: "serif" },
  { name: "Arbutus Slab", category: "serif" },
  { name: "Aref Ruqaa", category: "serif" },
  { name: "Argenta", category: "serif" },
  { name: "Arvo", category: "serif" },
  { name: "Average", category: "serif" },
  { name: "Baskervville", category: "serif" },
  { name: "Belgrano", category: "serif" },
  { name: "Bentham", category: "serif" },
  { name: "Bitter", category: "serif" },
  { name: "Bodoni Moda", category: "serif" },
  { name: "Bona Nova", category: "serif" },
  { name: "Brygada 1918", category: "serif" },
  { name: "Buenard", category: "serif" },
  { name: "Cactus Classical Serif", category: "serif" },
  { name: "Caladea", category: "serif" },
  { name: "Cambay", category: "serif" },
  { name: "Cambo", category: "serif" },
  { name: "Cantata One", category: "serif" },
  { name: "Cardo", category: "serif" },
  { name: "Castoro", category: "serif" },
  { name: "Castoro Titling", category: "serif" },
  { name: "Charis SIL", category: "serif" },
  { name: "Cinzel", category: "serif" },
  { name: "Cinzel Decorative", category: "serif" },
  { name: "Coelacanth", category: "serif" },
  { name: "Corben", category: "serif" },
  { name: "Cormorant", category: "serif" },
  { name: "Cormorant Garamond", category: "serif" },
  { name: "Cormorant Infant", category: "serif" },
  { name: "Cormorant SC", category: "serif" },
  { name: "Cormorant Unicase", category: "serif" },
  { name: "Cormorant Upright", category: "serif" },
  { name: "Coustard", category: "serif" },
  { name: "Crimson Pro", category: "serif" },
  { name: "Crimson Text", category: "serif" },
  { name: "DM Serif Display", category: "serif" },
  { name: "DM Serif Text", category: "serif" },
  { name: "Dalla Hand", category: "serif" },
  { name: "David Libre", category: "serif" },
  { name: "Della Respira", category: "serif" },
  { name: "Domine", category: "serif" },
  { name: "Donegal One", category: "serif" },
  { name: "EB Garamond", category: "serif" },
  { name: "Eczar", category: "serif" },
  { name: "El Messiri", category: "serif" },
  { name: "Enriqueta", category: "serif" },
  { name: "Erode", category: "serif" },
  { name: "Faustina", category: "serif" },
  { name: "Fenix", category: "serif" },
  { name: "Fjord One", category: "serif" },
  { name: "Frank Ruhl Libre", category: "serif" },
  { name: "Fraunces", category: "serif" },
  { name: "Gabriela", category: "serif" },
  { name: "Gelasio", category: "serif" },
  { name: "Gentium Book Plus", category: "serif" },
  { name: "Gentium Plus", category: "serif" },
  { name: "Gloock", category: "serif" },
  { name: "Goudy Bookletter 1911", category: "serif" },
  { name: "Gowun Batang", category: "serif" },
  { name: "Gowun Dodum", category: "serif" },
  { name: "Hahmlet", category: "serif" },
  { name: "Halant", category: "serif" },
  { name: "Hanuman", category: "serif" },
  { name: "Headland One", category: "serif" },
  { name: "IBM Plex Serif", category: "serif" },
  { name: "IM Fell DW Pica", category: "serif" },
  { name: "IM Fell DW Pica SC", category: "serif" },
  { name: "IM Fell Double Pica", category: "serif" },
  { name: "IM Fell Double Pica SC", category: "serif" },
  { name: "IM Fell English", category: "serif" },
  { name: "IM Fell English SC", category: "serif" },
  { name: "IM Fell French Canon", category: "serif" },
  { name: "IM Fell French Canon SC", category: "serif" },
  { name: "IM Fell Great Primer", category: "serif" },
  { name: "IM Fell Great Primer SC", category: "serif" },
  { name: "Inika", category: "serif" },
  { name: "Instrument Serif", category: "serif" },
  { name: "Italiana", category: "serif" },
  { name: "Jacques Francois", category: "serif" },
  { name: "Josefin Slab", category: "serif" },
  { name: "Judson", category: "serif" },
  { name: "Junge", category: "serif" },
  { name: "Kadwa", category: "serif" },
  { name: "Kameron", category: "serif" },
  { name: "Karma", category: "serif" },
  { name: "Kotta One", category: "serif" },
  { name: "Kurale", category: "serif" },
  { name: "Laila", category: "serif" },
  { name: "Lancelot", category: "serif" },
  { name: "Ledger", category: "serif" },
  { name: "Libre Baskerville", category: "serif" },
  { name: "Libre Bodoni", category: "serif" },
  { name: "Libre Caslon Display", category: "serif" },
  { name: "Libre Caslon Text", category: "serif" },
  { name: "Literata", category: "serif" },
  { name: "Lora", category: "serif" },
  { name: "Lusitana", category: "serif" },
  { name: "Lustria", category: "serif" },
  { name: "Marcellus", category: "serif" },
  { name: "Marcellus SC", category: "serif" },
  { name: "Marko One", category: "serif" },
  { name: "Mate", category: "serif" },
  { name: "Mate SC", category: "serif" },
  { name: "Merriweather", category: "serif" },
  { name: "Nanum Myeongjo", category: "serif" },
  { name: "Newsreader", category: "serif" },
  { name: "Noticia Text", category: "serif" },
  { name: "Noto Serif", category: "serif" },
  { name: "Noto Serif Bengali", category: "serif" },
  { name: "Noto Serif Devanagari", category: "serif" },
  { name: "Noto Serif Display", category: "serif" },
  { name: "Noto Serif Georgian", category: "serif" },
  { name: "Noto Serif HK", category: "serif" },
  { name: "Noto Serif Hebrew", category: "serif" },
  { name: "Noto Serif JP", category: "serif" },
  { name: "Noto Serif KR", category: "serif" },
  { name: "Noto Serif SC", category: "serif" },
  { name: "Noto Serif TC", category: "serif" },
  { name: "Noto Serif Tamil", category: "serif" },
  { name: "Noto Serif Telugu", category: "serif" },
  { name: "Noto Serif Thai", category: "serif" },
  { name: "Oleo Script", category: "serif" },
  { name: "Old Standard TT", category: "serif" },
  { name: "Oranienbaum", category: "serif" },
  { name: "PT Serif", category: "serif" },
  { name: "PT Serif Caption", category: "serif" },
  { name: "Petrona", category: "serif" },
  { name: "Piazzolla", category: "serif" },
  { name: "Playfair", category: "serif" },
  { name: "Playfair Display", category: "serif" },
  { name: "Playfair Display SC", category: "serif" },
  { name: "Podkova", category: "serif" },
  { name: "Poly", category: "serif" },
  { name: "Port Lligat Slab", category: "serif" },
  { name: "Prata", category: "serif" },
  { name: "Quando", category: "serif" },
  { name: "Quattrocento", category: "serif" },
  { name: "Radley", category: "serif" },
  { name: "Rasa", category: "serif" },
  { name: "Roboto Slab", category: "serif" },
  { name: "Rokkitt", category: "serif" },
  { name: "Rosarivo", category: "serif" },
  { name: "Rufina", category: "serif" },
  { name: "STIX Two Text", category: "serif" },
  { name: "Sanchez", category: "serif" },
  { name: "Sawarabi Mincho", category: "serif" },
  { name: "Scheherazade New", category: "serif" },
  { name: "Scope One", category: "serif" },
  { name: "Sedan", category: "serif" },
  { name: "Sedan SC", category: "serif" },
  { name: "Slabo 13px", category: "serif" },
  { name: "Slabo 27px", category: "serif" },
  { name: "Sorts Mill Goudy", category: "serif" },
  { name: "Source Serif 4", category: "serif" },
  { name: "Spectral", category: "serif" },
  { name: "Spectral SC", category: "serif" },
  { name: "Stint Ultra Expanded", category: "serif" },
  { name: "Suranna", category: "serif" },
  { name: "Suravaram", category: "serif" },
  { name: "Taviraj", category: "serif" },
  { name: "Tinos", category: "serif" },
  { name: "Tiro Bangla", category: "serif" },
  { name: "Tiro Devanagari Hindi", category: "serif" },
  { name: "Tiro Devanagari Marathi", category: "serif" },
  { name: "Tiro Devanagari Sanskrit", category: "serif" },
  { name: "Tiro Gurmukhi", category: "serif" },
  { name: "Tiro Kannada", category: "serif" },
  { name: "Tiro Tamil", category: "serif" },
  { name: "Tiro Telugu", category: "serif" },
  { name: "Trirong", category: "serif" },
  { name: "Unna", category: "serif" },
  { name: "Vesper Libre", category: "serif" },
  { name: "Vidaloka", category: "serif" },
  { name: "Volkhov", category: "serif" },
  { name: "Vollkorn", category: "serif" },
  { name: "Vollkorn SC", category: "serif" },
  { name: "Young Serif", category: "serif" },
  { name: "Zilla Slab", category: "serif" },
  { name: "Zilla Slab Highlight", category: "serif" },

  // ── Display ─────────────────────────────────────────────
  { name: "Abril Fatface", category: "display" },
  { name: "Acme", category: "display" },
  { name: "Aguafina Script", category: "display" },
  { name: "Akronim", category: "display" },
  { name: "Alfa Slab One", category: "display" },
  { name: "Almendra", category: "display" },
  { name: "Almendra Display", category: "display" },
  { name: "Amarante", category: "display" },
  { name: "Amita", category: "display" },
  { name: "Angkor", category: "display" },
  { name: "Arbutus", category: "display" },
  { name: "Astloch", category: "display" },
  { name: "Atma", category: "display" },
  { name: "Atomic Age", category: "display" },
  { name: "Audiowide", category: "display" },
  { name: "Autour One", category: "display" },
  { name: "Averia Gruesa Libre", category: "display" },
  { name: "Averia Libre", category: "display" },
  { name: "Averia Sans Libre", category: "display" },
  { name: "Averia Serif Libre", category: "display" },
  { name: "Bab", category: "display" },
  { name: "Bahiana", category: "display" },
  { name: "Bahianita", category: "display" },
  { name: "Bai Jamjuree", category: "display" },
  { name: "Baloo 2", category: "display" },
  { name: "Baloo Bhai 2", category: "display" },
  { name: "Baloo Bhaijaan 2", category: "display" },
  { name: "Baloo Chettan 2", category: "display" },
  { name: "Baloo Da 2", category: "display" },
  { name: "Baloo Paaji 2", category: "display" },
  { name: "Baloo Tamma 2", category: "display" },
  { name: "Baloo Tammudu 2", category: "display" },
  { name: "Baloo Thambi 2", category: "display" },
  { name: "Bangers", category: "display" },
  { name: "Baumans", category: "display" },
  { name: "Bebas Neue", category: "display" },
  { name: "Belanosima", category: "display" },
  { name: "Berkshire Swash", category: "display" },
  { name: "Bevan", category: "display" },
  { name: "Big Shoulders Display", category: "display" },
  { name: "Big Shoulders Inline Display", category: "display" },
  { name: "Big Shoulders Inline Text", category: "display" },
  { name: "Big Shoulders Stencil Display", category: "display" },
  { name: "Big Shoulders Stencil Text", category: "display" },
  { name: "Big Shoulders Text", category: "display" },
  { name: "Bigelow Rules", category: "display" },
  { name: "Black And White Picture", category: "display" },
  { name: "Black Ops One", category: "display" },
  { name: "Boogaloo", category: "display" },
  { name: "Bowlby One", category: "display" },
  { name: "Bowlby One SC", category: "display" },
  { name: "Bree Serif", category: "display" },
  { name: "Bruno Ace", category: "display" },
  { name: "Bruno Ace SC", category: "display" },
  { name: "Bungee", category: "display" },
  { name: "Bungee Hairline", category: "display" },
  { name: "Bungee Inline", category: "display" },
  { name: "Bungee Outline", category: "display" },
  { name: "Bungee Shade", category: "display" },
  { name: "Bungee Spice", category: "display" },
  { name: "Butcherman", category: "display" },
  { name: "Cabin Sketch", category: "display" },
  { name: "Caesar Dressing", category: "display" },
  { name: "Cagliostro", category: "display" },
  { name: "Carter One", category: "display" },
  { name: "Catamaran", category: "display" },
  { name: "Ceviche One", category: "display" },
  { name: "Changa One", category: "display" },
  { name: "Chango", category: "display" },
  { name: "Chelsea Market", category: "display" },
  { name: "Chenla", category: "display" },
  { name: "Cherry Cream Soda", category: "display" },
  { name: "Cherry Swash", category: "display" },
  { name: "Chewy", category: "display" },
  { name: "Chicle", category: "display" },
  { name: "Chonburi", category: "display" },
  { name: "Cinzel Decorative", category: "display" },
  { name: "Climate Crisis", category: "display" },
  { name: "Coda", category: "display" },
  { name: "Codystar", category: "display" },
  { name: "Combo", category: "display" },
  { name: "Concert One", category: "display" },
  { name: "Content", category: "display" },
  { name: "Contrail One", category: "display" },
  { name: "Corben", category: "display" },
  { name: "Creepster", category: "display" },
  { name: "Croissant One", category: "display" },
  { name: "Crushed", category: "display" },
  { name: "Dangrek", category: "display" },
  { name: "Diplomata", category: "display" },
  { name: "Diplomata SC", category: "display" },
  { name: "Dokdo", category: "display" },
  { name: "Dynalight", category: "display" },
  { name: "Eater", category: "display" },
  { name: "Emblema One", category: "display" },
  { name: "Emilys Candy", category: "display" },
  { name: "Ewert", category: "display" },
  { name: "Fascinate", category: "display" },
  { name: "Fascinate Inline", category: "display" },
  { name: "Faster One", category: "display" },
  { name: "Feasterville", category: "display" },
  { name: "Finger Paint", category: "display" },
  { name: "Flamenco", category: "display" },
  { name: "Flavors", category: "display" },
  { name: "Fontdiner Swanky", category: "display" },
  { name: "Forum", category: "display" },
  { name: "Fredericka the Great", category: "display" },
  { name: "Fredoka One", category: "display" },
  { name: "Freehand", category: "display" },
  { name: "Freckle Face", category: "display" },
  { name: "Fruktur", category: "display" },
  { name: "Fugaz One", category: "display" },
  { name: "Galada", category: "display" },
  { name: "Galindo", category: "display" },
  { name: "Gasoek One", category: "display" },
  { name: "Geostar", category: "display" },
  { name: "Geostar Fill", category: "display" },
  { name: "Germania One", category: "display" },
  { name: "Gideon Roman", category: "display" },
  { name: "Gorditas", category: "display" },
  { name: "Graduate", category: "display" },
  { name: "Gravitas One", category: "display" },
  { name: "Griffy", category: "display" },
  { name: "Gruppo", category: "display" },
  { name: "Gudea", category: "display" },
  { name: "Gugi", category: "display" },
  { name: "Gwendolyn", category: "display" },
  { name: "Habibi", category: "display" },
  { name: "Hanalei", category: "display" },
  { name: "Hanalei Fill", category: "display" },
  { name: "Happy Monkey", category: "display" },
  { name: "Henny Penny", category: "display" },
  { name: "Honk", category: "display" },
  { name: "Iceland", category: "display" },
  { name: "Irish Grover", category: "display" },
  { name: "Jacques Francois Shadow", category: "display" },
  { name: "Jockey One", category: "display" },
  { name: "Jolly Lodger", category: "display" },
  { name: "Jomhuria", category: "display" },
  { name: "Jomolhari", category: "display" },
  { name: "Kablammo", category: "display" },
  { name: "Kavoon", category: "display" },
  { name: "Kdam Thmor Pro", category: "display" },
  { name: "Keania One", category: "display" },
  { name: "Kelly Slab", category: "display" },
  { name: "Kenia", category: "display" },
  { name: "Knewave", category: "display" },
  { name: "Kranky", category: "display" },
  { name: "Lacquer", category: "display" },
  { name: "Lemon", category: "display" },
  { name: "Lemonada", category: "display" },
  { name: "Libre Barcode 128", category: "display" },
  { name: "Libre Barcode 128 Text", category: "display" },
  { name: "Libre Barcode 39", category: "display" },
  { name: "Libre Barcode 39 Extended", category: "display" },
  { name: "Libre Barcode 39 Extended Text", category: "display" },
  { name: "Libre Barcode 39 Text", category: "display" },
  { name: "Libre Barcode EAN13 Text", category: "display" },
  { name: "Lilita One", category: "display" },
  { name: "Limelight", category: "display" },
  { name: "Lobster", category: "display" },
  { name: "Lobster Two", category: "display" },
  { name: "Londrina Outline", category: "display" },
  { name: "Londrina Shadow", category: "display" },
  { name: "Londrina Sketch", category: "display" },
  { name: "Londrina Solid", category: "display" },
  { name: "Love Ya Like A Sister", category: "display" },
  { name: "Loved by the King", category: "display" },
  { name: "Luckiest Guy", category: "display" },
  { name: "Macondo", category: "display" },
  { name: "Macondo Swash Caps", category: "display" },
  { name: "Marhey", category: "display" },
  { name: "McLaren", category: "display" },
  { name: "MedievalSharp", category: "display" },
  { name: "Mega", category: "display" },
  { name: "Metal", category: "display" },
  { name: "Metal Mania", category: "display" },
  { name: "Metamorphous", category: "display" },
  { name: "Micro 5", category: "display" },
  { name: "Miltonian", category: "display" },
  { name: "Miltonian Tattoo", category: "display" },
  { name: "Mogra", category: "display" },
  { name: "Monoton", category: "display" },
  { name: "Monofett", category: "display" },
  { name: "Mystery Quest", category: "display" },
  { name: "New Rocker", category: "display" },
  { name: "Nixie One", category: "display" },
  { name: "Nosifer", category: "display" },
  { name: "Nova Cut", category: "display" },
  { name: "Nova Flat", category: "display" },
  { name: "Nova Mono", category: "display" },
  { name: "Nova Oval", category: "display" },
  { name: "Nova Round", category: "display" },
  { name: "Nova Script", category: "display" },
  { name: "Nova Slim", category: "display" },
  { name: "Nova Square", category: "display" },
  { name: "Offside", category: "display" },
  { name: "Oi", category: "display" },
  { name: "Oleo Script Swash Caps", category: "display" },
  { name: "Open Sans Condensed", category: "display" },
  { name: "Orienta", category: "display" },
  { name: "Original Surfer", category: "display" },
  { name: "Oswald", category: "display" },
  { name: "Overlock SC", category: "display" },
  { name: "Oxanium", category: "display" },
  { name: "Pacifico", category: "display" },
  { name: "Passero One", category: "display" },
  { name: "Passion One", category: "display" },
  { name: "Patua One", category: "display" },
  { name: "Peralta", category: "display" },
  { name: "Pirata One", category: "display" },
  { name: "Plaster", category: "display" },
  { name: "Poiret One", category: "display" },
  { name: "Poller One", category: "display" },
  { name: "Pompiere", category: "display" },
  { name: "Press Start 2P", category: "display" },
  { name: "Pridi", category: "display" },
  { name: "Racing Sans One", category: "display" },
  { name: "Rammetto One", category: "display" },
  { name: "Ranchers", category: "display" },
  { name: "Rationale", category: "display" },
  { name: "Ravi Prakash", category: "display" },
  { name: "Revalia", category: "display" },
  { name: "Ribeye", category: "display" },
  { name: "Ribeye Marrow", category: "display" },
  { name: "Righteous", category: "display" },
  { name: "Risque", category: "display" },
  { name: "Rowdies", category: "display" },
  { name: "Ruge Boogie", category: "display" },
  { name: "Rum Raisin", category: "display" },
  { name: "Ruslan Display", category: "display" },
  { name: "Rye", category: "display" },
  { name: "Sail", category: "display" },
  { name: "Salsa", category: "display" },
  { name: "Sancreek", category: "display" },
  { name: "Sansita", category: "display" },
  { name: "Sansita Swashed", category: "display" },
  { name: "Sawarabi Gothic", category: "display" },
  { name: "Sevillana", category: "display" },
  { name: "Shantell Sans", category: "display" },
  { name: "Shojumaru", category: "display" },
  { name: "Sigmar One", category: "display" },
  { name: "Sigmar", category: "display" },
  { name: "Silkscreen", category: "display" },
  { name: "Simonetta", category: "display" },
  { name: "Sirin Stencil", category: "display" },
  { name: "Slackey", category: "display" },
  { name: "Smokum", category: "display" },
  { name: "Smythe", category: "display" },
  { name: "Sniglet", category: "display" },
  { name: "Snippet", category: "display" },
  { name: "Snowburst One", category: "display" },
  { name: "Sofadi One", category: "display" },
  { name: "Sonsie One", category: "display" },
  { name: "Space Mono", category: "display" },
  { name: "Special Elite", category: "display" },
  { name: "Spicy Rice", category: "display" },
  { name: "Spirax", category: "display" },
  { name: "Squada One", category: "display" },
  { name: "Stalinist One", category: "display" },
  { name: "Stardos Stencil", category: "display" },
  { name: "Stick No Bills", category: "display" },
  { name: "Sticknobills", category: "display" },
  { name: "Strait", category: "display" },
  { name: "Supermercado One", category: "display" },
  { name: "Suwannaphum", category: "display" },
  { name: "Trade Winds", category: "display" },
  { name: "Trochut", category: "display" },
  { name: "Tulpen One", category: "display" },
  { name: "Turret Road", category: "display" },
  { name: "Ultra", category: "display" },
  { name: "Uncial Antiqua", category: "display" },
  { name: "UnifrakturCook", category: "display" },
  { name: "UnifrakturMaguntia", category: "display" },
  { name: "Unlock", category: "display" },
  { name: "Vampiro One", category: "display" },
  { name: "Vast Shadow", category: "display" },
  { name: "Viaoda Libre", category: "display" },
  { name: "Voces", category: "display" },
  { name: "Vujahday Script", category: "display" },
  { name: "Wallpoet", category: "display" },
  { name: "Warnes", category: "display" },
  { name: "Wellfleet", category: "display" },
  { name: "Wendy One", category: "display" },
  { name: "Wire One", category: "display" },
  { name: "Yatra One", category: "display" },
  { name: "Yeseva One", category: "display" },
  { name: "Yesteryear", category: "display" },
  { name: "Zen Dots", category: "display" },
  { name: "Zen Tokyo Zoo", category: "display" },
  { name: "Zeyada", category: "display" },

  // ── Handwriting ──────────────────────────────────────────
  { name: "Aclonica", category: "handwriting" },
  { name: "ADLaM Display", category: "handwriting" },
  { name: "Alex Brush", category: "handwriting" },
  { name: "Allison", category: "handwriting" },
  { name: "Allura", category: "handwriting" },
  { name: "Amatic SC", category: "handwriting" },
  { name: "Amiri Quran", category: "handwriting" },
  { name: "Annie Use Your Telescope", category: "handwriting" },
  { name: "Architects Daughter", category: "handwriting" },
  { name: "Arizonia", category: "handwriting" },
  { name: "Bad Script", category: "handwriting" },
  { name: "Ballet", category: "handwriting" },
  { name: "Bilbo", category: "handwriting" },
  { name: "Bilbo Swash Caps", category: "handwriting" },
  { name: "Bonbon", category: "handwriting" },
  { name: "Bonheur Royale", category: "handwriting" },
  { name: "Borel", category: "handwriting" },
  { name: "Butterfly Kids", category: "handwriting" },
  { name: "Calligraffitti", category: "handwriting" },
  { name: "Caramel", category: "handwriting" },
  { name: "Caveat", category: "handwriting" },
  { name: "Caveat Brush", category: "handwriting" },
  { name: "Cedarville Cursive", category: "handwriting" },
  { name: "Charm", category: "handwriting" },
  { name: "Clicker Script", category: "handwriting" },
  { name: "Coiny", category: "handwriting" },
  { name: "Comforter", category: "handwriting" },
  { name: "Comforter Brush", category: "handwriting" },
  { name: "Comic Neue", category: "handwriting" },
  { name: "Coming Soon", category: "handwriting" },
  { name: "Cookie", category: "handwriting" },
  { name: "Corinthia", category: "handwriting" },
  { name: "Courgette", category: "handwriting" },
  { name: "Covered By Your Grace", category: "handwriting" },
  { name: "Crafty Girls", category: "handwriting" },
  { name: "Damion", category: "handwriting" },
  { name: "Dancing Script", category: "handwriting" },
  { name: "Dawning of a New Day", category: "handwriting" },
  { name: "Dekko", category: "handwriting" },
  { name: "Delicious Handrawn", category: "handwriting" },
  { name: "Delius", category: "handwriting" },
  { name: "Delius Swash Caps", category: "handwriting" },
  { name: "Delius Unicase", category: "handwriting" },
  { name: "Devonshire", category: "handwriting" },
  { name: "Dr Sugiyama", category: "handwriting" },
  { name: "Eagle Lake", category: "handwriting" },
  { name: "East Sea Dokdo", category: "handwriting" },
  { name: "Edu AU VIC WA NT Hand", category: "handwriting" },
  { name: "Edu NSW ACT Foundation", category: "handwriting" },
  { name: "Edu QLD Beginner", category: "handwriting" },
  { name: "Edu SA Beginner", category: "handwriting" },
  { name: "Edu TAS Beginner", category: "handwriting" },
  { name: "Edu VIC WA NT Beginner", category: "handwriting" },
  { name: "Engagement", category: "handwriting" },
  { name: "Estonia", category: "handwriting" },
  { name: "Euphoria Script", category: "handwriting" },
  { name: "Expletus Sans", category: "handwriting" },
  { name: "Felipa", category: "handwriting" },
  { name: "Festive", category: "handwriting" },
  { name: "Fleur De Leah", category: "handwriting" },
  { name: "Flow Block", category: "handwriting" },
  { name: "Flow Circular", category: "handwriting" },
  { name: "Flow Rounded", category: "handwriting" },
  { name: "Fondamento", category: "handwriting" },
  { name: "Fuzzy Bubbles", category: "handwriting" },
  { name: "Gaegu", category: "handwriting" },
  { name: "Gamja Flower", category: "handwriting" },
  { name: "Give You Glory", category: "handwriting" },
  { name: "Glass Antiqua", category: "handwriting" },
  { name: "Gloria Hallelujah", category: "handwriting" },
  { name: "Glory", category: "handwriting" },
  { name: "Gochi Hand", category: "handwriting" },
  { name: "Grand Hotel", category: "handwriting" },
  { name: "Great Vibes", category: "handwriting" },
  { name: "Grechen Fuemen", category: "handwriting" },
  { name: "Gwendolyn", category: "handwriting" },
  { name: "Handlee", category: "handwriting" },
  { name: "Henny Penny", category: "handwriting" },
  { name: "Herr Von Muellerhoff", category: "handwriting" },
  { name: "Hi Melody", category: "handwriting" },
  { name: "Homemade Apple", category: "handwriting" },
  { name: "Imperial Script", category: "handwriting" },
  { name: "Indie Flower", category: "handwriting" },
  { name: "Ingrid Darling", category: "handwriting" },
  { name: "Inspiration", category: "handwriting" },
  { name: "Island Moments", category: "handwriting" },
  { name: "Italianno", category: "handwriting" },
  { name: "Jim Nightshade", category: "handwriting" },
  { name: "Julee", category: "handwriting" },
  { name: "Just Another Hand", category: "handwriting" },
  { name: "Just Me Again Down Here", category: "handwriting" },
  { name: "Kalam", category: "handwriting" },
  { name: "Kaushan Script", category: "handwriting" },
  { name: "Kavivanar", category: "handwriting" },
  { name: "Kenia", category: "handwriting" },
  { name: "Kite One", category: "handwriting" },
  { name: "Kolker Brush", category: "handwriting" },
  { name: "Kotta One", category: "handwriting" },
  { name: "Kristi", category: "handwriting" },
  { name: "La Belle Aurore", category: "handwriting" },
  { name: "Lakki Reddy", category: "handwriting" },
  { name: "League Script", category: "handwriting" },
  { name: "Leckerli One", category: "handwriting" },
  { name: "Licorice", category: "handwriting" },
  { name: "Liu Jian Mao Cao", category: "handwriting" },
  { name: "Long Cang", category: "handwriting" },
  { name: "Love Light", category: "handwriting" },
  { name: "Loved by the King", category: "handwriting" },
  { name: "Lovers Quarrel", category: "handwriting" },
  { name: "Luxurious Roman", category: "handwriting" },
  { name: "Luxurious Script", category: "handwriting" },
  { name: "Ma Shan Zheng", category: "handwriting" },
  { name: "Maitree", category: "handwriting" },
  { name: "Mansalva", category: "handwriting" },
  { name: "Marck Script", category: "handwriting" },
  { name: "Mea Culpa", category: "handwriting" },
  { name: "Meie Script", category: "handwriting" },
  { name: "Merienda", category: "handwriting" },
  { name: "Merienda One", category: "handwriting" },
  { name: "Mervale Script", category: "handwriting" },
  { name: "Miniver", category: "handwriting" },
  { name: "Miss Fajardose", category: "handwriting" },
  { name: "Molle", category: "handwriting" },
  { name: "Monsieur La Doulaise", category: "handwriting" },
  { name: "Montaga", category: "handwriting" },
  { name: "Montez", category: "handwriting" },
  { name: "Mr Bedfort", category: "handwriting" },
  { name: "Mr Dafoe", category: "handwriting" },
  { name: "Mr De Haviland", category: "handwriting" },
  { name: "Mrs Saint Delafield", category: "handwriting" },
  { name: "Mrs Sheppards", category: "handwriting" },
  { name: "Ms Madi", category: "handwriting" },
  { name: "Mynerve", category: "handwriting" },
  { name: "Nanum Brush Script", category: "handwriting" },
  { name: "Nanum Pen Script", category: "handwriting" },
  { name: "Neonderthaw", category: "handwriting" },
  { name: "Neucha", category: "handwriting" },
  { name: "Niconne", category: "handwriting" },
  { name: "Norican", category: "handwriting" },
  { name: "Nothing You Could Do", category: "handwriting" },
  { name: "Oooh Baby", category: "handwriting" },
  { name: "Over the Rainbow", category: "handwriting" },
  { name: "Pacifico", category: "handwriting" },
  { name: "Pangolin", category: "handwriting" },
  { name: "Parisienne", category: "handwriting" },
  { name: "Patrick Hand", category: "handwriting" },
  { name: "Patrick Hand SC", category: "handwriting" },
  { name: "Pattaya", category: "handwriting" },
  { name: "Petemoss", category: "handwriting" },
  { name: "Petit Formal Script", category: "handwriting" },
  { name: "Pinyon Script", category: "handwriting" },
  { name: "Princess Sofia", category: "handwriting" },
  { name: "Qwigley", category: "handwriting" },
  { name: "Qwitcher Grypen", category: "handwriting" },
  { name: "Rancho", category: "handwriting" },
  { name: "Redacted Script", category: "handwriting" },
  { name: "Reenie Beanie", category: "handwriting" },
  { name: "Rock Salt", category: "handwriting" },
  { name: "Rochester", category: "handwriting" },
  { name: "Rouge Script", category: "handwriting" },
  { name: "Ruge Boogie", category: "handwriting" },
  { name: "Ruthie", category: "handwriting" },
  { name: "Sacramento", category: "handwriting" },
  { name: "Sail", category: "handwriting" },
  { name: "Satisfy", category: "handwriting" },
  { name: "Schoolbell", category: "handwriting" },
  { name: "Sedgwick Ave", category: "handwriting" },
  { name: "Sedgwick Ave Display", category: "handwriting" },
  { name: "Send Flowers", category: "handwriting" },
  { name: "Shadows Into Light", category: "handwriting" },
  { name: "Shadows Into Light Two", category: "handwriting" },
  { name: "Shalimar", category: "handwriting" },
  { name: "Short Stack", category: "handwriting" },
  { name: "Sofia", category: "handwriting" },
  { name: "Song Myung", category: "handwriting" },
  { name: "Splash", category: "handwriting" },
  { name: "Square Peg", category: "handwriting" },
  { name: "Style Script", category: "handwriting" },
  { name: "Sue Ellen Francisco", category: "handwriting" },
  { name: "Sunshiney", category: "handwriting" },
  { name: "Swanky and Moo Moo", category: "handwriting" },
  { name: "Tangerine", category: "handwriting" },
  { name: "The Girl Next Door", category: "handwriting" },
  { name: "The Nautigal", category: "handwriting" },
  { name: "Tillana", category: "handwriting" },
  { name: "Twinkle Star", category: "handwriting" },
  { name: "Vibur", category: "handwriting" },
  { name: "Vujahday Script", category: "handwriting" },
  { name: "Waiting for the Sunrise", category: "handwriting" },
  { name: "Walter Turncoat", category: "handwriting" },
  { name: "Water Brush", category: "handwriting" },
  { name: "Waterfall", category: "handwriting" },
  { name: "Whisper", category: "handwriting" },
  { name: "WindSong", category: "handwriting" },
  { name: "Yellowtail", category: "handwriting" },
  { name: "Yeon Sung", category: "handwriting" },
  { name: "Zeyada", category: "handwriting" },
  { name: "Zhi Mang Xing", category: "handwriting" },

  // ── Monospace ────────────────────────────────────────────
  { name: "Anonymous Pro", category: "monospace" },
  { name: "Azeret Mono", category: "monospace" },
  { name: "B612 Mono", category: "monospace" },
  { name: "Chivo Mono", category: "monospace" },
  { name: "Courier Prime", category: "monospace" },
  { name: "Cousine", category: "monospace" },
  { name: "Cutive Mono", category: "monospace" },
  { name: "DM Mono", category: "monospace" },
  { name: "Droid Sans Mono", category: "monospace" },
  { name: "Fira Code", category: "monospace" },
  { name: "Fira Mono", category: "monospace" },
  { name: "Geist Mono", category: "monospace" },
  { name: "IBM Plex Mono", category: "monospace" },
  { name: "Inconsolata", category: "monospace" },
  { name: "JetBrains Mono", category: "monospace" },
  { name: "Major Mono Display", category: "monospace" },
  { name: "Martian Mono", category: "monospace" },
  { name: "Nanum Gothic Coding", category: "monospace" },
  { name: "Noto Sans Mono", category: "monospace" },
  { name: "Nova Mono", category: "monospace" },
  { name: "Overpass Mono", category: "monospace" },
  { name: "Oxygen Mono", category: "monospace" },
  { name: "PT Mono", category: "monospace" },
  { name: "Red Hat Mono", category: "monospace" },
  { name: "Roboto Mono", category: "monospace" },
  { name: "Share Tech Mono", category: "monospace" },
  { name: "Source Code Pro", category: "monospace" },
  { name: "Space Mono", category: "monospace" },
  { name: "Spline Sans Mono", category: "monospace" },
  { name: "Syne Mono", category: "monospace" },
  { name: "Ubuntu Mono", category: "monospace" },
  { name: "Ubuntu Sans Mono", category: "monospace" },
  { name: "VT323", category: "monospace" },
  { name: "Xanh Mono", category: "monospace" },
];

// Deduplicate by name (some fonts appear in multiple categories above)
const seen = new Set<string>();
export const GOOGLE_FONTS_DEDUPED: GoogleFontEntry[] = GOOGLE_FONTS_FULL.filter(f => {
  if (seen.has(f.name)) return false;
  seen.add(f.name);
  return true;
});

export const GOOGLE_FONT_CATEGORIES = ['handwriting', 'serif', 'sans-serif', 'display', 'monospace'] as const;

export const GOOGLE_FONT_CATEGORY_LABELS: Record<string, string> = {
  'handwriting': 'Handwriting & Script',
  'serif': 'Serif',
  'sans-serif': 'Sans-Serif',
  'display': 'Display & Decorative',
  'monospace': 'Monospace',
};
