project_id = "xytxkidpourwdbzzwcdp"

[functions.create-media-upload-url]
verify_jwt = false

[functions.confirm-media-upload]
verify_jwt = false

[functions.check-stream-video-status]
verify_jwt = false

[functions.moderate-media]
verify_jwt = true

[functions.export-gallery-zip]
verify_jwt = true

[functions.start-multipart-upload]
verify_jwt = false

[functions.complete-multipart-upload]
verify_jwt = false
