project_id = "xytxkidpourwdbzzwcdp"

[functions.send-auth-email]
verify_jwt = false

[functions.generate-seating-suggestions]
verify_jwt = true

[functions.create-welcome-video-upload]
verify_jwt = true

[functions.check-welcome-video-status]
verify_jwt = true
