import React from 'react';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { AdminAccountLifecyclePage, AdminCustomersPage, AdminEventsPage, AdminOverviewPage, AdminSubscriptionsPaymentsPage } from './AdminCentrePages';

const mocks=vi.hoisted(()=>({rpc:vi.fn(),invoke:vi.fn()}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{rpc:mocks.rpc,functions:{invoke:mocks.invoke}}}));
const snapshot={generated_at:'2026-08-19T00:00:00Z',customers:[{id:'host-1',full_name:'Alex Host',email:'alex@example.com',mobile:null,signup_date:'2026-08-18',email_confirmed_at:'2026-08-18',last_sign_in_at:'2026-08-19',customer_type:'host',account_status:'active',plan_name:'Premium',plan_status:'active',plan_started_at:'2026-08-18',plan_expires_at:'2027-08-18',event_count:2},{id:'vendor-1',full_name:'Venue Co',email:'venue@example.com',mobile:null,signup_date:'2026-08-01',email_confirmed_at:null,last_sign_in_at:null,customer_type:'vendor',account_status:'suspended',plan_name:'Vendor Pro',plan_status:'pending_approval',plan_started_at:'2026-08-01',plan_expires_at:'2026-09-01',event_count:0}],subscriptions:[{id:'sub-1',user_id:'host-1',customer_name:'Alex Host',email:'alex@example.com',plan_name:'Starter Trial',price_aud:0,subscription_status:'trialing',payment_status:'recorded',started_at:'2026-08-18',expires_at:'2026-08-22',created_at:'2026-08-18',is_read_only:false,vendor_approval_status:'not_applicable'},{id:'sub-2',user_id:'vendor-1',customer_name:'Venue Co',email:'venue@example.com',plan_name:'Vendor Pro',price_aud:100,subscription_status:'pending_approval',payment_status:'recorded',started_at:'2026-08-01',expires_at:'2026-09-01',created_at:'2026-08-01',is_read_only:true,vendor_approval_status:'pending'}],events:[{id:'event-1',user_id:'host-1',name:'Alex Wedding',event_type:'wedding',effective_date:'2026-09-20',venue:'Harbour Room',created_at:'2026-08-10',owner_name:'Alex Host',owner_email:'alex@example.com',guest_count:80,invitations_sent:25,attending_count:18,plan_name:'Premium',event_status:'upcoming'}],lifecycle:[{account_owner_id:'closed-1',customer_name:'Closed Customer',email:'closed@example.com',status:'scheduled_for_deletion',deletion_requested_at:'2026-08-01',purge_after:'2027-08-01',reactivated_at:null,stripe_cancellation_succeeded:false,deletion_processing_error:'private diagnostic',updated_at:'2026-08-01',previous_plan:'Premium',purge_status:'scheduled'}],payments:[],recent_admin_actions:[],configuration:{account_lifecycle:true,admin_actions:true,stripe_live_data:false}};
describe('Admin Centre operational pages',()=>{
  beforeEach(()=>{mocks.rpc.mockReset();mocks.invoke.mockReset();mocks.rpc.mockResolvedValue({data:snapshot,error:null});mocks.invoke.mockResolvedValue({data:{success:true},error:null});});
  it('keeps free trials separate from active paid customers',async()=>{render(<MemoryRouter><AdminOverviewPage/></MemoryRouter>);expect(await screen.findByText('Active free trials')).toBeInTheDocument();expect(screen.getByText('Active paid customers')).toBeInTheDocument();});
  it('filters Vendors & Venues without duplicating closed accounts',async()=>{render(<MemoryRouter><AdminCustomersPage/></MemoryRouter>);await screen.findByText('Alex Host');fireEvent.change(screen.getByLabelText('Customer type'),{target:{value:'vendor'}});expect(screen.getByText('Venue Co')).toBeInTheDocument();expect(screen.queryByText('Alex Host')).not.toBeInTheDocument();expect(screen.queryByText('Closed Customer')).not.toBeInTheDocument();});
  it('renders actual subscription/payment states and filters event search',async()=>{const {unmount}=render(<MemoryRouter><AdminSubscriptionsPaymentsPage/></MemoryRouter>);expect(await screen.findByText('pending approval')).toBeInTheDocument();unmount();render(<MemoryRouter><AdminEventsPage/></MemoryRouter>);await screen.findByText('Alex Wedding');fireEvent.change(screen.getByLabelText('Search events'),{target:{value:'not present'}});expect(screen.getByText('No events match these filters.')).toBeInTheDocument();});
  it('shows a branded friendly lifecycle unavailable state without printing the raw database error',async()=>{mocks.rpc.mockResolvedValue({data:null,error:{code:'42883',message:'function get_account_closure_admin_summary does not exist'}});render(<MemoryRouter><AdminAccountLifecyclePage/></MemoryRouter>);expect(await screen.findByText('Admin data is temporarily unavailable')).toBeInTheDocument();expect(screen.queryByText(/get_account_closure_admin_summary/)).not.toBeInTheDocument();});
  it('requires confirmation and an audit reason before sensitive customer actions',async()=>{render(<MemoryRouter><AdminCustomersPage/></MemoryRouter>);await screen.findByText('Alex Host');fireEvent.click(screen.getByRole('button',{name:'Suspend'}));const confirm=screen.getByRole('button',{name:'Confirm action'});expect(confirm).toBeDisabled();fireEvent.change(screen.getByPlaceholderText('Required for the secure audit record'),{target:{value:'Fraud review requested'}});expect(confirm).toBeEnabled();fireEvent.click(confirm);await waitFor(()=>expect(mocks.invoke).toHaveBeenCalledWith('admin-account-action',expect.objectContaining({body:expect.objectContaining({action:'suspend',reason:'Fraud review requested'})})));});
});
