import React, { useState, useRef, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { Progress } from '@/components/ui/progress';
import { Camera, Upload, CheckCircle2 } from 'lucide-react';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';

export const GuestMediaUpload: React.FC = () => {
  const { eventSlug } = useParams<{ eventSlug: string }>();
  const { toast } = useToast();
  const fileInputRef = useRef<HTMLInputElement>(null);
  
  const [eventData, setEventData] = useState<any>(null);
  const [token, setToken] = useState<string | null>(null);
  const [uploading, setUploading] = useState(false);
  const [uploadProgress, setUploadProgress] = useState(0);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [caption, setCaption] = useState('');
  const [uploadSuccess, setUploadSuccess] = useState(false);

  // Fetch event data
  useEffect(() => {
    const fetchEventData = async () => {
      try {
        const { data, error } = await supabase
          .from('events')
          .select('id, name, date, venue')
          .eq('slug', eventSlug)
          .single();

        if (error) throw error;
        setEventData(data);

        // Generate or retrieve token for this guest
        const storedToken = localStorage.getItem(`media_token_${data.id}`);
        if (storedToken) {
          setToken(storedToken);
        } else {
          // In production, tokens would be generated by the host
          // For now, we'll create a simple token
          const newToken = `guest_${Date.now()}`;
          localStorage.setItem(`media_token_${data.id}`, newToken);
          setToken(newToken);
        }
      } catch (error: any) {
        console.error('Error fetching event:', error);
        toast({
          title: 'Error',
          description: 'Event not found',
          variant: 'destructive',
        });
      }
    };

    if (eventSlug) {
      fetchEventData();
    }
  }, [eventSlug]);

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      setSelectedFile(file);
      setUploadSuccess(false);
    }
  };

  const handleUpload = async () => {
    if (!selectedFile || !token || !eventData) return;

    setUploading(true);
    setUploadProgress(0);

    try {
      const fileType = selectedFile.type.startsWith('image/') ? 'image' : 'video';

      // Step 1: Get upload URL
      const { data: urlData, error: urlError } = await supabase.functions.invoke(
        'create-media-upload-url',
        {
          body: {
            event_id: eventData.id,
            token,
            type: fileType,
            file_name: selectedFile.name,
            file_size: selectedFile.size,
          },
        }
      );

      if (urlError) throw urlError;

      setUploadProgress(30);

      // Step 2: Upload file to storage
      const uploadResponse = await fetch(urlData.upload_url, {
        method: 'PUT',
        body: selectedFile,
        headers: {
          'Content-Type': selectedFile.type,
        },
      });

      if (!uploadResponse.ok) throw new Error('Upload failed');

      setUploadProgress(70);

      // Step 3: Get image dimensions if it's an image
      let width, height;
      if (fileType === 'image') {
        const img = new Image();
        img.src = URL.createObjectURL(selectedFile);
        await new Promise((resolve) => {
          img.onload = () => {
            width = img.width;
            height = img.height;
            resolve(null);
          };
        });
      }

      // Step 4: Confirm upload
      const { error: confirmError } = await supabase.functions.invoke(
        'confirm-media-upload',
        {
          body: {
            event_id: eventData.id,
            token,
            file_path: urlData.file_path,
            type: fileType,
            caption: caption || null,
            width,
            height,
            file_size: selectedFile.size,
            mime_type: selectedFile.type,
          },
        }
      );

      if (confirmError) throw confirmError;

      setUploadProgress(100);
      setUploadSuccess(true);
      setSelectedFile(null);
      setCaption('');

      toast({
        title: 'Upload Successful! 🎉',
        description: 'Thanks for sharing your memories!',
      });

    } catch (error: any) {
      console.error('Upload error:', error);
      toast({
        title: 'Upload Failed',
        description: error.message || 'Failed to upload media',
        variant: 'destructive',
      });
    } finally {
      setUploading(false);
    }
  };

  if (!eventData) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-subtle">
        <Card className="w-full max-w-md">
          <CardContent className="p-8 text-center">
            <p>Loading event...</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-subtle py-12 px-4">
      <div className="max-w-2xl mx-auto space-y-6">
        {/* Event Header */}
        <Card className="ww-box text-center">
          <CardHeader>
            <Camera className="w-16 h-16 mx-auto text-primary mb-4" />
            <CardTitle className="text-3xl">{eventData.name}</CardTitle>
            <p className="text-muted-foreground mt-2">
              Share your favorite moments from this special day!
            </p>
          </CardHeader>
        </Card>

        {/* Upload Form */}
        {!uploadSuccess ? (
          <Card className="ww-box">
            <CardContent className="p-8 space-y-6">
              <input
                ref={fileInputRef}
                type="file"
                accept="image/*,video/*"
                onChange={handleFileSelect}
                className="hidden"
              />

              {!selectedFile ? (
                <Button
                  variant="default"
                  size="lg"
                  className="w-full bg-gradient-primary hover:opacity-90"
                  onClick={() => fileInputRef.current?.click()}
                  disabled={uploading}
                >
                  <Camera className="w-5 h-5 mr-2" />
                  Choose Photo or Video
                </Button>
              ) : (
                <>
                  <div className="space-y-4">
                    <div className="p-4 bg-muted rounded-lg">
                      <p className="font-medium">{selectedFile.name}</p>
                      <p className="text-sm text-muted-foreground">
                        {(selectedFile.size / (1024 * 1024)).toFixed(2)} MB
                      </p>
                    </div>

                    <div className="space-y-2">
                      <label className="text-sm font-medium">
                        Add a caption (optional)
                      </label>
                      <Textarea
                        value={caption}
                        onChange={(e) => setCaption(e.target.value)}
                        placeholder="Tell us about this moment..."
                        rows={3}
                        disabled={uploading}
                      />
                    </div>

                    {uploading && (
                      <div className="space-y-2">
                        <Progress value={uploadProgress} />
                        <p className="text-sm text-center text-muted-foreground">
                          Uploading... {uploadProgress}%
                        </p>
                      </div>
                    )}

                    <div className="flex gap-3">
                      <Button
                        variant="outline"
                        className="flex-1"
                        onClick={() => {
                          setSelectedFile(null);
                          setCaption('');
                        }}
                        disabled={uploading}
                      >
                        Cancel
                      </Button>
                      <Button
                        variant="default"
                        className="flex-1 bg-gradient-primary hover:opacity-90"
                        onClick={handleUpload}
                        disabled={uploading}
                      >
                        <Upload className="w-4 h-4 mr-2" />
                        Upload
                      </Button>
                    </div>
                  </div>
                </>
              )}
            </CardContent>
          </Card>
        ) : (
          <Card className="ww-box">
            <CardContent className="p-12 text-center space-y-4">
              <CheckCircle2 className="w-20 h-20 mx-auto text-success" />
              <h2 className="text-2xl font-bold">Thank You! 🎉</h2>
              <p className="text-muted-foreground">
                Your photo/video has been uploaded and is awaiting approval.
              </p>
              <Button
                variant="default"
                className="bg-gradient-primary hover:opacity-90"
                onClick={() => {
                  setUploadSuccess(false);
                  fileInputRef.current?.click();
                }}
              >
                Upload Another
              </Button>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
};