ALTER TABLE place_card_settings
  ADD COLUMN IF NOT EXISTS info_bold BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS info_italic BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS info_underline BOOLEAN NOT NULL DEFAULT false;