-- Add Canva-style image variant columns to the 3 sign studio settings tables.
-- These columns hold the URLs and pixel dimensions for the 3 variants
-- generated by the optimize-image edge function on upload:
--   - background_image_url           = master (full resolution, used for PDF export)
--   - background_image_preview_url   = ~2400px JPEG q=0.92 (used by live editor preview)
--   - background_image_thumb_url     = ~400px JPEG q=0.75  (used by gallery cards)
--   - background_image_width_px / height_px = original master dimensions (for 300 DPI upscale warning)

ALTER TABLE public.invitation_card_settings
  ADD COLUMN IF NOT EXISTS background_image_preview_url text,
  ADD COLUMN IF NOT EXISTS background_image_thumb_url   text,
  ADD COLUMN IF NOT EXISTS background_image_width_px    integer,
  ADD COLUMN IF NOT EXISTS background_image_height_px   integer;

ALTER TABLE public.place_card_settings
  ADD COLUMN IF NOT EXISTS background_image_preview_url text,
  ADD COLUMN IF NOT EXISTS background_image_thumb_url   text,
  ADD COLUMN IF NOT EXISTS background_image_width_px    integer,
  ADD COLUMN IF NOT EXISTS background_image_height_px   integer;

ALTER TABLE public.signage_settings
  ADD COLUMN IF NOT EXISTS background_image_preview_url text,
  ADD COLUMN IF NOT EXISTS background_image_thumb_url   text,
  ADD COLUMN IF NOT EXISTS background_image_width_px    integer,
  ADD COLUMN IF NOT EXISTS background_image_height_px   integer;